USE CAR;
ALTER TABLE CAR_DETAILS
ADD PRIMARY KEY (SR);

ALTER TABLE FEATURE
ADD primary key (MODEL);

ALTER TABLE CAR_DETAILS
ADD foreign key (MODEL)
REFERENCES FEATURE(MODEL);

/*
ALTER TABLE ORDER_DETAILS
ADD foreign key (MODEL)
references FEATURE(MODEL);
*/

ALTER TABLE ORDER_DETAILS
ADD primary key (ORDER_NO);

ALTER TABLE POST_ORDER_DETAILS
ADD primary key (NO_PLATE);

ALTER TABLE POST_ORDER_DETAILS
ADD FOREIGN KEY (ORDER_NO)
REFERENCES ORDER_DETAILS(ORDER_NO);

